# Taller Práctico: Limpieza de Datos con Pandas y Polars

## Objetivo
En este taller, aprenderás a realizar tareas fundamentales de limpieza de datos utilizando dos de las librerías más potentes en Python: **Pandas** y **Polars**. El objetivo es que entiendas las diferencias y similitudes entre ambas, y cómo manejar datasets del mundo real que suelen estar "sucios" (valores faltantes, tipos de datos incorrectos, duplicados, etc.).

## 1. Selección del Dataset
Para realizar esta práctica, necesitarás descargar un dataset de Kaggle. Te propongo las siguientes opciones (elige una):

1.  **Used Cars Dataset**: Contiene información sobre coches de segunda mano. Es ideal porque suele tener columnas con texto "sucio" (e.g., precios con símbolos de moneda, kilometraje con unidades) y valores nulos.
    *   *Búsqueda en Kaggle*: "Used Cars Dataset" (ej. el de Austin Reese).
2.  **Netflix Movies and TV Shows**: Contiene metadatos de contenido de Netflix. Perfecto para practicar limpieza de cadenas de texto (directores, actores) y manejo de fechas.
    *   *Búsqueda en Kaggle*: "Netflix Movies and TV Shows".
3.  **San Francisco Building Permits**: Un dataset más grande y "desordenado", con muchos valores nulos y tipos de datos mezclados.
    *   *Búsqueda en Kaggle*: "San Francisco Building Permits".

**Instrucciones:**
1.  Descarga el archivo CSV de tu elección desde Kaggle.
2.  Colócalo en la misma carpeta que este notebook (o en una subcarpeta `data/`).
3.  Renómbralo a algo sencillo, por ejemplo: `dataset.csv`.

## 2. Instalación e Importación de Librerías
Asegúrate de tener instaladas las librerías necesarias. Descomenta la siguiente línea si necesitas instalarlas.

In [2]:
# !pip install pandas polars matplotlib seaborn

In [3]:
import pandas as pd
import polars as pl
import numpy as np

## 3. Carga de Datos

### 3.1 Cargar con Pandas
Carga el dataset utilizando Pandas y muestra las primeras 5 filas.

In [6]:
df_pandas = pd.read_csv('netflix_titles.csv')
df_pandas.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

### 3.2 Cargar con Polars
Realiza la misma operación utilizando Polars.

In [8]:
# Tu código aquí (Polars)
df_polars = pl.read_csv('netflix_titles.csv') # Ajusta el nombre del archivo
df_polars.head()

shape: (5, 12)
┌─────────┬─────────┬─────────────┬─────────────┬───┬────────┬───────────┬────────────┬────────────┐
│ show_id ┆ type    ┆ title       ┆ director    ┆ … ┆ rating ┆ duration  ┆ listed_in  ┆ descriptio │
│ ---     ┆ ---     ┆ ---         ┆ ---         ┆   ┆ ---    ┆ ---       ┆ ---        ┆ n          │
│ str     ┆ str     ┆ str         ┆ str         ┆   ┆ str    ┆ str       ┆ str        ┆ ---        │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆            ┆ str        │
╞═════════╪═════════╪═════════════╪═════════════╪═══╪════════╪═══════════╪════════════╪════════════╡
│ s1      ┆ Movie   ┆ Dick        ┆ Kirsten     ┆ … ┆ PG-13  ┆ 90 min    ┆ Documentar ┆ As her     │
│         ┆         ┆ Johnson Is  ┆ Johnson     ┆   ┆        ┆           ┆ ies        ┆ father     │
│         ┆         ┆ Dead        ┆             ┆   ┆        ┆           ┆            ┆ nears the  │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆            ┆ end of…    │
│ s2      ┆ TV Show ┆ Blood &     ┆ null        ┆ … ┆ TV-MA  ┆ 2 Seasons ┆ Internatio ┆ After      │
│         ┆         ┆ Water       ┆             ┆   ┆        ┆           ┆ nal TV     ┆ crossing   │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆ Shows, TV  ┆ paths at a │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆ Dra…       ┆ part…      │
│ s3      ┆ TV Show ┆ Ganglands   ┆ Julien      ┆ … ┆ TV-MA  ┆ 1 Season  ┆ Crime TV   ┆ To protect │
│         ┆         ┆             ┆ Leclercq    ┆   ┆        ┆           ┆ Shows, Int ┆ his family │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆ ernational ┆ from a p…  │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆ …          ┆            │
│ s4      ┆ TV Show ┆ Jailbirds   ┆ null        ┆ … ┆ TV-MA  ┆ 1 Season  ┆ Docuseries ┆ Feuds, fli │
│         ┆         ┆ New Orleans ┆             ┆   ┆        ┆           ┆ , Reality  ┆ rtations   │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆ TV         ┆ and toilet │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆            ┆ …          │
│ s5      ┆ TV Show ┆ Kota        ┆ null        ┆ … ┆ TV-MA  ┆ 2 Seasons ┆ Internatio ┆ In a city  │
│         ┆         ┆ Factory     ┆             ┆   ┆        ┆           ┆ nal TV     ┆ of         │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆ Shows,     ┆ coaching   │
│         ┆         ┆             ┆             ┆   ┆        ┆           ┆ Romant…    ┆ centers …  │
└─────────┴─────────┴─────────────┴─────────────┴───┴────────┴───────────┴────────────┴────────────┘

## 4. Inspección General del Dataset

Antes de limpiar, debemos conocer los datos.
**Tarea:** Muestra la información general (tipos de datos, columnas) y estadísticas descriptivas básicas.

In [9]:
# Pandas: info() y describe()
print("--- Pandas Info ---")
df_pandas.info()

print("\n--- Pandas Describe ---")
print(df_pandas.describe(include='all'))

--- Pandas Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

--- Pandas Describe ---
       show_id   type   title       director                cast  \
count     8807   8807    8807           6173                7982
unique    8807      2    8807           4528                7692
top      s8807  Movie  Zubaan  Rajiv Chilaka  David Attenborough
freq         1   6131       1             19                  19
mean       NaN    NaN     NaN            NaN                 NaN
std        NaN    NaN     NaN            NaN                 NaN
min        NaN    NaN     NaN            NaN                 NaN
25%        NaN    NaN     NaN            NaN                 NaN
50%        NaN    NaN     NaN            NaN                 NaN
75%        NaN    NaN     NaN            NaN                 NaN
max        NaN    NaN     NaN            NaN                 NaN

              country       date_added  release_year rating  duration  \
count            7976             8797   8807.000000   8803      8804
unique            748             1767           NaN     17       220
top     United States  January 1, 2020           NaN  TV-MA  1 Season
freq             2818              109           NaN   3207      1793
mean              NaN              NaN   2014.180198    NaN       NaN
std               NaN              NaN      8.819312    NaN       NaN
min               NaN              NaN   1925.000000    NaN       NaN
25%               NaN              NaN   2013.000000    NaN       NaN
50%               NaN              NaN   2017.000000    NaN       NaN
75%               NaN              NaN   2019.000000    NaN       NaN
max               NaN              NaN   2021.000000    NaN       NaN

                           listed_in  \
count                           8807
unique                           514
top     Dramas, International Movies
freq                             362
mean                             NaN
std                              NaN
min                              NaN
25%                              NaN
50%                              NaN
75%                              NaN
max                              NaN

                                              description
count                                                8807
unique                                               8775
top     Paranormal activity at a lush, abandoned prope...
freq                                                    4
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

In [11]:
# Polars: describe() y glimpse() (si prefieres)
print("--- Polars Describe ---")
print(df_polars.describe())

print("\n--- Polars Glimpse ---")
print(df_polars.glimpse())

--- Polars Describe ---
shape: (9, 13)
┌────────────┬─────────┬─────────┬─────────────┬───┬────────┬──────────┬─────────────┬─────────────┐
│ statistic  ┆ show_id ┆ type    ┆ title       ┆ … ┆ rating ┆ duration ┆ listed_in   ┆ description │
│ ---        ┆ ---     ┆ ---     ┆ ---         ┆   ┆ ---    ┆ ---      ┆ ---         ┆ ---         │
│ str        ┆ str     ┆ str     ┆ str         ┆   ┆ str    ┆ str      ┆ str         ┆ str         │
╞════════════╪═════════╪═════════╪═════════════╪═══╪════════╪══════════╪═════════════╪═════════════╡
│ count      ┆ 8807    ┆ 8807    ┆ 8807        ┆ … ┆ 8803   ┆ 8804     ┆ 8807        ┆ 8807        │
│ null_count ┆ 0       ┆ 0       ┆ 0           ┆ … ┆ 4      ┆ 3        ┆ 0           ┆ 0           │
│ mean       ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ std        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ min        ┆ s1      ┆ Movie   ┆ #Alive      ┆ … ┆ 66 min ┆ 1 Season ┆ Action &    ┆ "Bridgerton │
│            ┆         ┆         ┆             ┆   ┆        ┆          ┆ Adventure   ┆ " cast      │
│            ┆         ┆         ┆             ┆   ┆        ┆          ┆             ┆ members     │
│            ┆         ┆         ┆             ┆   ┆        ┆          ┆             ┆ shar…       │
│ 25%        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ 50%        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ 75%        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ max        ┆ s999    ┆ TV Show ┆ 최강전사    ┆ … ┆ UR     ┆ 99 min   ┆ Thrillers   ┆ “Last       │
│            ┆         ┆         ┆ 미니특공대  ┆   ┆        ┆          ┆             ┆ Chance U”   │
│            ┆         ┆         ┆ : 영웅의    ┆   ┆        ┆          ┆             ┆ hits the    │
│            ┆         ┆         ┆ 탄생        ┆   ┆        ┆          ┆             ┆ hardw…      │
└────────────┴─────────┴─────────┴─────────────┴───┴────────┴──────────┴─────────────┴─────────────┘

--- Polars Glimpse ---
Rows: 8807
Columns: 12
$ show_id      <str> 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10'
$ type         <str> 'Movie', 'TV Show', 'TV Show', 'TV Show', 'TV Show', 'TV Show', 'Movie', 'Movie', 'TV Show', 'Movie'
$ title        <str> 'Dick Johnson Is Dead', 'Blood & Water', 'Ganglands', 'Jailbirds New Orleans', 'Kota Factory', 'Midnight Mass', 'My Little Pony: A New Generation', 'Sankofa', 'The Great British Baking Show', 'The Starling'
$ director     <str> 'Kirsten Johnson', None, 'Julien Leclercq', None, None, 'Mike Flanagan', 'Robert Cullen, José Luis Ucha', 'Haile Gerima', 'Andy Devonshire', 'Theodore Melfi'
$ cast         <str> None, 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng', 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera', None, 'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar', 'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver', 'Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr', 'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri', 'Mel Giedroyc, Sue Perkins, Mary Berry, Paul Hollywood', "Melissa McCarthy, Chris O'Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor"
$ country      <str> 'United States', 'South Africa', None, None, 'India', None, None, 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia', 'United Kingdom', 'United States'
$ date_added   <str> 'September 25, 2021', 'September 24, 2021', 'September 24, 2021', 'September 24, 2021', 'September 24, 2021', 'September 24, 2021', 'September 24, 2021', 'September 24, 2021', 'September 24, 2021', 'September 24, 2021'
$ release_year <i64> 2020, 2021, 2021, 2021, 2021, 2021, 2021, 1993, 2021, 2021
$ rating       <str> 'PG-13', 'TV-MA', 'TV-MA', 'TV-MA', 'TV-MA', 'TV-MA', 'PG', 'TV-MA', 'TV-14', 'PG-13'
$ duration     <str> '90 min', '2 Seasons', '1 Season', '1 Season', '2 Seasons', '1 Season', '91 min', '125 min', '9 Seasons', '104 min'
$ listed_in    <str> 'Documentaries', 'International TV Shows, TV Dramas, TV Mysteries', 'Crime TV Shows, International TV Shows, TV Action & Adventure', 'Docuseries, Reality TV', 'International TV Shows, Romantic TV Shows, TV Comedies', 'TV Dramas, TV Horror, TV Mysteries', 'Children & Family Movies', 'Dramas, Independent Movies, International Movies', 'British TV Shows, Reality TV', 'Comedies, Dramas'
$ description  <str> 'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.', 'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.', 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.', 'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.', 'In a city of coaching centers known to train India’s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.', 'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.', "Equestria's divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals — and, hoof to heart, she’s determined to prove it.", 'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.', "A talented batch of amateur bakers face off in a 10-week competition, whipping up their best dishes in the hopes of being named the U.K.'s best.", "A woman adjusting to life after a loss contends with a feisty bird that's taken over her garden — and a husband who's struggling to find a way forward."

None

## 5. Manejo de Valores Faltantes (Nulls/NaNs)

Los datos reales raramente están completos.
**Tarea:**
1.  Cuenta cuántos valores nulos hay por columna.
2.  Decide una estrategia para una columna importante con nulos (e.g., rellenar con la media, moda, o un valor fijo como "Desconocido", o eliminar las filas).
3.  Aplica esa estrategia.

In [12]:
# --- PANDAS ---
print("Nulos por columna:")
print(df_pandas.isnull().sum())

cols_fillna = ['director', 'cast', 'country']
df_pandas[cols_fillna] = df_pandas[cols_fillna].fillna("Unknown")

df_pandas = df_pandas.dropna(subset=['date_added'])

print("\nNulos tras limpieza:")
print(df_pandas.isnull().sum())

Nulos por columna:
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

Nulos tras limpieza:
show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          4
duration        3
listed_in       0
description     0
dtype: int64

In [14]:
# --- POLARS ---
print("Nulos por columna:")
print(df_polars.null_count())

df_polars = df_polars.with_columns([
    pl.col("director").fill_null("Unknown"),
    pl.col("cast").fill_null("Unknown"),
    pl.col("country").fill_null("Unknown")
]).drop_nulls(subset=["date_added"])

print("\nNulos tras limpieza:")
print(df_polars.null_count())

Nulos por columna:
shape: (1, 12)
┌─────────┬──────┬───────┬──────────┬───┬────────┬──────────┬───────────┬─────────────┐
│ show_id ┆ type ┆ title ┆ director ┆ … ┆ rating ┆ duration ┆ listed_in ┆ description │
│ ---     ┆ ---  ┆ ---   ┆ ---      ┆   ┆ ---    ┆ ---      ┆ ---       ┆ ---         │
│ u32     ┆ u32  ┆ u32   ┆ u32      ┆   ┆ u32    ┆ u32      ┆ u32       ┆ u32         │
╞═════════╪══════╪═══════╪══════════╪═══╪════════╪══════════╪═══════════╪═════════════╡
│ 0       ┆ 0    ┆ 0     ┆ 2634     ┆ … ┆ 4      ┆ 3        ┆ 0         ┆ 0           │
└─────────┴──────┴───────┴──────────┴───┴────────┴──────────┴───────────┴─────────────┘

Nulos tras limpieza:
shape: (1, 12)
┌─────────┬──────┬───────┬──────────┬───┬────────┬──────────┬───────────┬─────────────┐
│ show_id ┆ type ┆ title ┆ director ┆ … ┆ rating ┆ duration ┆ listed_in ┆ description │
│ ---     ┆ ---  ┆ ---   ┆ ---      ┆   ┆ ---    ┆ ---      ┆ ---       ┆ ---         │
│ u32     ┆ u32  ┆ u32   ┆ u32      ┆   ┆ u32    ┆ u32      ┆ u32       ┆ u32         │
╞═════════╪══════╪═══════╪══════════╪═══╪════════╪══════════╪═══════════╪═════════════╡
│ 0       ┆ 0    ┆ 0     ┆ 0        ┆ … ┆ 4      ┆ 3        ┆ 0         ┆ 0           │
└─────────┴──────┴───────┴──────────┴───┴────────┴──────────┴───────────┴─────────────┘

## 6. Manejo de Duplicados

**Tarea:** Verifica si existen filas totalmente duplicadas y elimínalas.

In [15]:
# --- PANDAS ---
# Verificar y eliminar duplicados
duplicados = df_pandas.duplicated(subset=['show_id']).sum()
print(f"Duplicados encontrados: {duplicados}")

df_pandas = df_pandas.drop_duplicates(subset=['show_id'])

Duplicados encontrados: 0

In [17]:
# --- POLARS ---
# Verificar y eliminar duplicados (unique)
n_dupes = df_polars.height - df_polars.unique(subset=["show_id"]).height
print(f"Duplicados encontrados: {n_dupes}")

df_polars = df_polars.unique(subset=["show_id"])

Duplicados encontrados: 0

## 7. Transformación de Datos y Limpieza de Strings

A menudo, los números vienen como texto (e.g., "$1,000", "50 kg") o las fechas no tienen el formato correcto.

**Tarea (Ejemplo Genérico):**
1.  Selecciona una columna de tipo string que debería ser numérica o fecha.
2.  Limpia el string (quita símbolos como '$', 'kg', ',').
3.  Convierte la columna al tipo correcto (int, float, o datetime).

*Nota: Si elegiste el dataset de coches, la columna de 'precio' o 'kilometraje' es ideal para esto.*

In [18]:
# --- PANDAS ---
df_pandas['date_added'] = df_pandas['date_added'].str.strip()
df_pandas['date_added_clean'] = pd.to_datetime(df_pandas['date_added'], errors='coerce')

df_pandas['duration_val'] = df_pandas['duration'].astype(str).str.extract(r'(\d+)').astype(float)

print(df_pandas[['date_added', 'date_added_clean', 'duration', 'duration_val']].head())

           date_added date_added_clean   duration  duration_val
0  September 25, 2021       2021-09-25     90 min          90.0
1  September 24, 2021       2021-09-24  2 Seasons           2.0
2  September 24, 2021       2021-09-24   1 Season           1.0
3  September 24, 2021       2021-09-24   1 Season           1.0
4  September 24, 2021       2021-09-24  2 Seasons           2.0

In [19]:
# --- POLARS ---
df_polars = df_polars.with_columns([
    pl.col("date_added")
      .str.strip_chars()
      .str.to_date("%B %d, %Y", strict=False)
      .alias("date_added_clean"),

    pl.col("duration")
      .str.extract(r"(\d+)", 1)
      .cast(pl.Int64, strict=False)
      .alias("duration_val")
])

print(df_polars.select(['date_added', 'date_added_clean', 'duration', 'duration_val']).head())

shape: (5, 4)
┌───────────────────┬──────────────────┬───────────┬──────────────┐
│ date_added        ┆ date_added_clean ┆ duration  ┆ duration_val │
│ ---               ┆ ---              ┆ ---       ┆ ---          │
│ str               ┆ date             ┆ str       ┆ i64          │
╞═══════════════════╪══════════════════╪═══════════╪══════════════╡
│  July 1, 2017     ┆ 2017-07-01       ┆ 8 Seasons ┆ 8            │
│ October 9, 2020   ┆ 2020-10-09       ┆ 126 min   ┆ 126          │
│ December 11, 2015 ┆ 2015-12-11       ┆ 120 min   ┆ 120          │
│ March 17, 2019    ┆ 2019-03-17       ┆ 1 Season  ┆ 1            │
│ April 20, 2021    ┆ 2021-04-20       ┆ 80 min    ┆ 80           │
└───────────────────┴──────────────────┴───────────┴──────────────┘

## 8. Conclusiones y Comparativa

Escribe brevemente tus conclusiones:
- ¿Qué librería te pareció más intuitiva?
- ¿Notaste alguna diferencia de velocidad (si el dataset era grande)?
- ¿Qué dificultades encontraste en la limpieza?

En cuanto a la intuición, Polars me resultó más organizada para definir el flujo de limpieza; su sintaxis encadenada (.with_columns) hace que el código sea más legible que las múltiples reasignaciones de variables necesarias en Pandas. Sobre el rendimiento, aunque el dataset no es masivo, la ejecución en Polars se siente más optimizada, especialmente al convertir fechas, donde su enfoque estricto evita la sobrecarga de inferencia que hace Pandas.

La mayor dificultad fue limpiar columnas mixtas como duration y parsear date_added. Mientras que Pandas es más permisivo y "mágico", Polars obliga a ser explícito con los formatos de fecha y los tipos de datos. Esto añade una pequeña barrera inicial, pero a cambio ofrece un pipeline mucho más robusto y menos propenso a errores silenciosos.

## 9. Guardar el Dataset Limpio
Finalmente, guarda el dataset limpio en un nuevo archivo CSV.

In [ ]:
# Pandas
df_pandas.to_csv('netflix_limpio_pandas.csv', index=False)

# Polars
df_polars.write_csv('netflix_limpio_polars.csv')